export const Moedas = [
  { code: 'USD-BRL', name: 'Dólar Americano/Real Brasileiro' },
  { code: 'BRL-USD', name: 'Real Brasileiro/Dólar Americano' },
  { code: 'EUR-BRL', name: 'Euro/Real Brasileiro' },
  { code: 'BRL-EUR', name: 'Real Brasileiro/Euro' },
  { code: 'GBP-BRL', name: 'Libra Esterlina/Real Brasileiro' },
  { code: 'ARS-BRL', name: 'Peso Argentino/Real Brasileiro' },
  { code: 'BTC-BRL', name: 'Bitcoin/Real Brasileiro' },
  { code: 'LTC-BRL', name: 'Litecoin/Real Brasileiro' },
  { code: 'JPY-BRL', name: 'Iene Japonês/Real Brasileiro' },
  { code: 'CHF-BRL', name: 'Franco Suíço/Real Brasileiro' },
  { code: 'AUD-BRL', name: 'Dólar Australiano/Real Brasileiro' },
  { code: 'CNY-BRL', name: 'Yuan Chinês/Real Brasileiro' },
  { code: 'ILS-BRL', name: 'Novo Shekel Israelense/Real Brasileiro' },
  { code: 'ETH-BRL', name: 'Ethereum/Real Brasileiro' },
  { code: 'XRP-BRL', name: 'XRP/Real Brasileiro' },
  { code: 'EUR-USD', name: 'Euro/Dólar Americano' },
  { code: 'CAD-USD', name: 'Dólar Canadense/Dólar Americano' },
  { code: 'GBP-USD', name: 'Libra Esterlina/Dólar Americano' },
  { code: 'ARS-USD', name: 'Peso Argentino/Dólar Americano' },
  { code: 'JPY-USD', name: 'Iene Japonês/Dólar Americano' },
  { code: 'CHF-USD', name: 'Franco Suíço/Dólar Americano' },
  { code: 'AUD-USD', name: 'Dólar Australiano/Dólar Americano' },
  { code: 'CNY-USD', name: 'Yuan Chinês/Dólar Americano' },
  { code: 'ILS-USD', name: 'Novo Shekel Israelense/Dólar Americano' },
  { code: 'BTC-USD', name: 'Bitcoin/Dólar Americano' },
  { code: 'LTC-USD', name: 'Litecoin/Dólar Americano' },
  { code: 'ETH-USD', name: 'Ethereum/Dólar Americano' },
  { code: 'XRP-USD', name: 'XRP/Dólar Americano' },
  { code: 'BRL-USD', name: 'Real Brasileiro/Dólar Americano' },
  { code: 'BRL-EUR', name: 'Real Brasileiro/Euro' },
  { code: 'USD-EUR', name: 'Dólar Americano/Euro' },
  { code: 'CAD-EUR', name: 'Dólar Canadense/Euro' },
  { code: 'GBP-EUR', name: 'Libra Esterlina/Euro' },
  { code: 'ARS-EUR', name: 'Peso Argentino/Euro' },
  { code: 'JPY-EUR', name: 'Iene Japonês/Euro' },
  { code: 'CHF-EUR', name: 'Franco Suíço/Euro' },
  { code: 'AUD-EUR', name: 'Dólar Australiano/Euro' },
  { code: 'CNY-EUR', name: 'Yuan Chinês/Euro' },
  { code: 'ILS-EUR', name: 'Novo Shekel Israelense/Euro' },
  { code: 'BTC-EUR', name: 'Bitcoin/Euro' },
  { code: 'LTC-EUR', name: 'Litecoin/Euro' },
  { code: 'ETH-EUR', name: 'Ethereum/Euro' },
  { code: 'XRP-EUR', name: 'XRP/Euro' },
  { code: 'DOGE-BRL', name: 'Dogecoin/Real Brasileiro' },
  { code: 'DOGE-EUR', name: 'Dogecoin/Euro' },
  { code: 'DOGE-USD', name: 'Dogecoin/Dólar Americano' },
  { code: 'USD-JPY', name: 'Dólar Americano/Iene Japonês' },
  { code: 'USD-CHF', name: 'Dólar Americano/Franco Suíço' },
  { code: 'USD-CAD', name: 'Dólar Americano/Dólar Canadense' },
  { code: 'NZD-USD', name: 'Dólar Neozelandês/Dólar Americano' },
  { code: 'USD-ZAR', name: 'Dólar Americano/Rand Sul-Africano' },
  { code: 'USD-TRY', name: 'Dólar Americano/Nova Lira Turca' },
  { code: 'USD-MXN', name: 'Dólar Americano/Peso Mexicano' },
  { code: 'USD-PLN', name: 'Dólar Americano/Zlóti Polonês' },
  { code: 'USD-SEK', name: 'Dólar Americano/Coroa Sueca' },
  { code: 'USD-SGD', name: 'Dólar Americano/Dólar de Cingapura' },
  { code: 'USD-DKK', name: 'Dólar Americano/Coroa Dinamarquesa' },
  { code: 'USD-NOK', name: 'Dólar Americano/Coroa Norueguesa' },
  { code: 'USD-ILS', name: 'Dólar Americano/Novo Shekel Israelense' },
  { code: 'USD-HUF', name: 'Dólar Americano/Florim Húngaro' },
  { code: 'USD-CZK', name: 'Dólar Americano/Coroa Checa' },
  { code: 'USD-THB', name: 'Dólar Americano/Baht Tailandês' },
  { code: 'USD-AED', name: 'Dólar Americano/Dirham dos Emirados' },
  { code: 'USD-JOD', name: 'Dólar Americano/Dinar Jordaniano' },
  { code: 'USD-KWD', name: 'Dólar Americano/Dinar Kuwaitiano' },
  { code: 'USD-HKD', name: 'Dólar Americano/Dólar de Hong Kong' },
  { code: 'USD-SAR', name: 'Dólar Americano/Riyal Saudita' },
  { code: 'USD-INR', name: 'Dólar Americano/Rúpia Indiana' },
  { code: 'USD-KRW', name: 'Dólar Americano/Won Sul-Coreano' },
  { code: 'FJD-USD', name: 'Dólar de Fiji/Dólar Americano' },
  { code: 'GHS-USD', name: 'Cedi Ganês/Dólar Americano' },
  { code: 'KYD-USD', name: 'Dólar das Ilhas Cayman/Dólar Americano' },
  { code: 'SGD-USD', name: 'Dólar de Cingapura/Dólar Americano' },
  { code: 'USD-ALL', name: 'Dólar Americano/Lek Albanês' },
  { code: 'USD-AMD', name: 'Dólar Americano/Dram Armênio' },
  { code: 'USD-ANG', name: 'Dólar Americano/Guilder das Antilhas' },
  { code: 'USD-ARS', name: 'Dólar Americano/Peso Argentino' },
  { code: 'USD-AUD', name: 'Dólar Americano/Dólar Australiano' },
  { code: 'USD-BBD', name: 'Dólar Americano/Dólar de Barbados' },
  { code: 'USD-BDT', name: 'Dólar Americano/Taka de Bangladesh' },
  { code: 'USD-BGN', name: 'Dólar Americano/Lev Búlgaro' },
  { code: 'USD-BHD', name: 'Dólar Americano/Dinar do Bahrein' },
  { code: 'USD-BIF', name: 'Dólar Americano/Franco Burundinense' },
  { code: 'USD-BND', name: 'Dólar Americano/Dólar de Brunei' },
  { code: 'USD-BOB', name: 'Dólar Americano/Boliviano' },
  { code: 'USD-BSD', name: 'Dólar Americano/Dólar das Bahamas' },
  { code: 'USD-BWP', name: 'Dólar Americano/Pula de Botswana' },
  { code: 'USD-BZD', name: 'Dólar Americano/Dólar de Belize' },
  { code: 'USD-CLP', name: 'Dólar Americano/Peso Chileno' },
  { code: 'USD-CNY', name: 'Dólar Americano/Yuan Chinês' },
  { code: 'USD-COP', name: 'Dólar Americano/Peso Colombiano' },
  { code: 'USD-CRC', name: 'Dólar Americano/Colón Costarriquenho' },
  { code: 'USD-CUP', name: 'Dólar Americano/Peso Cubano' },
  { code: 'USD-DJF', name: 'Dólar Americano/Franco do Djubouti' },
  { code: 'USD-DOP', name: 'Dólar Americano/Peso Dominicano' },
  { code: 'USD-DZD', name: 'Dólar Americano/Dinar Argelino' },
  { code: 'USD-EGP', name: 'Dólar Americano/Libra Egípcia' },
  { code: 'USD-ETB', name: 'Dólar Americano/Birr Etíope' },
  { code: 'USD-FJD', name: 'Dólar Americano/Dólar de Fiji' },
  { code: 'USD-GBP', name: 'Dólar Americano/Libra Esterlina' },
  { code: 'USD-GEL', name: 'Dólar Americano/Lari Georgiano' },
  { code: 'USD-GHS', name: 'Dólar Americano/Cedi Ganês' },
  { code: 'USD-GMD', name: 'Dólar Americano/Dalasi da Gâmbia' },
  { code: 'USD-GNF', name: 'Dólar Americano/Franco de Guiné' },
  { code: 'USD-GTQ', name: 'Dólar Americano/Quetzal Guatemalteco' },
  { code: 'USD-HNL', name: 'Dólar Americano/Lempira Hondurenha' },
  { code: 'USD-HRK', name: 'Dólar Americano/Kuna Croata' },
  { code: 'USD-HTG', name: 'Dólar Americano/Gourde Haitiano' },
  { code: 'USD-IDR', name: 'Dólar Americano/Rupia Indonésia' },
  { code: 'USD-IQD', name: 'Dólar Americano/Dinar Iraquiano' },
  { code: 'USD-IRR', name: 'Dólar Americano/Rial Iraniano' },
  { code: 'USD-ISK', name: 'Dólar Americano/Coroa Islandesa' },
  { code: 'USD-JMD', name: 'Dólar Americano/Dólar Jamaicano' },
  { code: 'USD-KES', name: 'Dólar Americano/Shilling Queniano' },
  { code: 'USD-KHR', name: 'Dólar Americano/Riel Cambojano' },
  { code: 'USD-KMF', name: 'Dólar Americano/Franco Comorense' },
  { code: 'EUR-NAD', name: 'Euro/Dólar Namíbio' },
  { code: 'EUR-NGN', name: 'Euro/Naira Nigeriana' },
  { code: 'EUR-NIO', name: 'Euro/Córdoba Nicaraguense' },
  { code: 'EUR-NPR', name: 'Euro/Rúpia Nepalesa' },
  { code: 'EUR-OMR', name: 'Euro/Rial Omanense' },
  { code: 'EUR-PAB', name: 'Euro/Balboa Panamenho' },
  { code: 'EUR-PEN', name: 'Euro/Sol do Peru' },
  { code: 'EUR-PGK', name: 'Euro/Kina Papua-Nova Guiné' },
  { code: 'EUR-PHP', name: 'Euro/Peso Filipino' },
  { code: 'EUR-PKR', name: 'Euro/Rúpia Paquistanesa' },
  { code: 'EUR-PYG', name: 'Euro/Guarani Paraguaio' },
  { code: 'EUR-QAR', name: 'Euro/Rial Catarense' },
  { code: 'EUR-RON', name: 'Euro/Leu Romeno' },
  { code: 'EUR-RSD', name: 'Euro/Dinar Sérvio' },
  { code: 'EUR-RWF', name: 'Euro/Franco Ruandês' },
  { code: 'EUR-SAR', name: 'Euro/Riyal Saudita' },
  { code: 'EUR-SCR', name: 'Euro/Rúpias de Seicheles' },
  { code: 'EUR-SDG', name: 'Euro/Libra Sudanesa' },
  { code: 'EUR-SDR', name: 'Euro/DSE' },
  { code: 'EUR-SOS', name: 'Euro/Shilling Somaliano' },
  { code: 'EUR-STD', name: 'Euro/Dobra São Tomé/Príncipe' },
  { code: 'EUR-SVC', name: 'Euro/Colon de El Salvador' },
  { code: 'EUR-SYP', name: 'Euro/Libra Síria' },
  { code: 'EUR-SZL', name: 'Euro/Lilangeni Suazilandês' },
  { code: 'EUR-TND', name: 'Euro/Dinar Tunisiano' },
  { code: 'EUR-TTD', name: 'Euro/Dólar de Trinidad' },
  { code: 'EUR-TWD', name: 'Euro/Dólar Taiuanês' },
  { code: 'EUR-TZS', name: 'Euro/Shilling Tanzaniano' },
  { code: 'EUR-UAH', name: 'Euro/Hryvinia Ucraniana' },
  { code: 'EUR-UGX', name: 'Euro/Shilling Ugandês' },
  { code: 'EUR-UYU', name: 'Euro/Peso Uruguaio' },
  { code: 'EUR-UZS', name: 'Euro/Som Uzbequistanês' },
  { code: 'EUR-VEF', name: 'Euro/Bolívar Venezuelano' },
  { code: 'EUR-VND', name: 'Euro/Dong Vietnamita' },
  { code: 'EUR-XAF', name: 'Euro/Franco CFA Central' },
  { code: 'EUR-XOF', name: 'Euro/Franco CFA Ocidental' },
  { code: 'EUR-XPF', name: 'Euro/Franco CFP' },
  { code: 'EUR-ZMK', name: 'Euro/Kwacha Zambiana' },
  { code: 'GHS-EUR', name: 'Cedi Ganês/Euro' },
  { code: 'NZD-EUR', name: 'Dólar Neozelandês/Euro' },
  { code: 'SGD-EUR', name: 'Dólar de Cingapura/Euro' },
  { code: 'AED-EUR', name: 'Dirham dos Emirados/Euro' },
  { code: 'DKK-EUR', name: 'Coroa Dinamarquesa/Euro' },
  { code: 'EUR-XCD', name: 'Euro/Dólar do Caribe Oriental' },
  { code: 'HKD-EUR', name: 'Dólar de Hong Kong/Euro' },
  { code: 'MXN-EUR', name: 'Peso Mexicano/Euro' },
  { code: 'NOK-EUR', name: 'Coroa Norueguesa/Euro' },
  { code: 'PLN-EUR', name: 'Zlóti Polonês/Euro' },
  { code: 'RUB-EUR', name: 'Rublo Russo/Euro' },
  { code: 'SAR-EUR', name: 'Riyal Saudita/Euro' },
  { code: 'SEK-EUR', name: 'Coroa Sueca/Euro' },
  { code: 'TRY-EUR', name: 'Nova Lira Turca/Euro' },
  { code: 'TWD-EUR', name: 'Dólar Taiuanês/Euro' },
  { code: 'VEF-EUR', name: 'Bolívar Venezuelano/Euro' },
  { code: 'ZAR-EUR', name: 'Rand Sul-Africano/Euro' },
  { code: 'MAD-EUR', name: 'Dirham Marroquino/Euro' },
  { code: 'KRW-EUR', name: 'Won Sul-Coreano/Euro' },
  { code: 'EGP-EUR', name: 'Libra Egípcia/Euro' },
  { code: 'EUR-MZN', name: 'Euro/Metical de Moçambique' },
  { code: 'INR-EUR', name: 'Rúpia Indiana/Euro' },
  { code: 'JOD-EUR', name: 'Dinar Jordaniano/Euro' },
  { code: 'KWD-EUR', name: 'Dinar Kuwaitiano/Euro' },
  { code: 'EUR-AZN', name: 'Euro/Manat Azeri' },
  { code: 'EUR-AMD', name: 'Euro/Dram Armênio' },
  { code: 'EUR-TJS', name: 'Euro/Somoni do Tajiquistão' },
  { code: 'EUR-RUB', name: 'Euro/Rublo Russo' },
  { code: 'HUF-EUR', name: 'Florim Húngaro/Euro' },
  { code: 'GEL-EUR', name: 'Lari Georgiano/Euro' },
  { code: 'EUR-GEL', name: 'Euro/Lari Georgiano' },
  { code: 'IDR-EUR', name: 'Rupia Indonésia/Euro' },
  { code: 'EUR-AOA', name: 'Euro/Kwanza Angolano' },
  { code: 'BYN-EUR', name: 'Rublo Bielorrusso/Euro' },
  { code: 'XAGG-EUR', name: 'Prata/Euro' },
  { code: 'PEN-EUR', name: 'Sol do Peru/Euro' },
  { code: 'XAGG-USD', name: 'Prata/Dólar Americano' },
  { code: 'USD-MNT', name: 'Dólar Americano/Mongolian Tugrik' },
  { code: 'USD-AFN', name: 'Dólar Americano/Afghani do Afeganistão' },
  { code: 'AFN-USD', name: 'Afghani do Afeganistão/Dólar Americano' },
  { code: 'SYP-USD', name: 'Libra Síria/Dólar Americano' },
  { code: 'IRR-USD', name: 'Rial Iraniano/Dólar Americano' },
  { code: 'IQD-USD', name: 'Dinar Iraquiano/Dólar Americano' },
  { code: 'USD-NGNI', name: 'Dólar Americano/Naira Nigeriana' },
  { code: 'USD-ZWL', name: 'Dólar Americano/Dólar Zimbabuense' },
  { code: 'BRL-ARS', name: 'Real Brasileiro/Peso Argentino' },
  { code: 'BRL-AUD', name: 'Real Brasileiro/Dólar Australiano' },
  { code: 'BRL-CAD', name: 'Real Brasileiro/Dólar Canadense' },
  { code: 'BRL-CHF', name: 'Real Brasileiro/Franco Suíço' },
  { code: 'BRL-CLP', name: 'Real Brasileiro/Peso Chileno' },
  { code: 'BRL-DKK', name: 'Real Brasileiro/Coroa Dinamarquesa' },
  { code: 'BRL-HKD', name: 'Real Brasileiro/Dólar de Hong Kong' },
  { code: 'BRL-JPY', name: 'Real Brasileiro/Iene Japonês' },
  { code: 'BRL-MXN', name: 'Real Brasileiro/Peso Mexicano' },
  { code: 'BRL-SGD', name: 'Real Brasileiro/Dólar de Cingapura' },
  { code: 'SGD-BRL', name: 'Dólar de Cingapura/Real Brasileiro' },
  { code: 'AED-BRL', name: 'Dirham dos Emirados/Real Brasileiro' },
  { code: 'BRL-AED', name: 'Real Brasileiro/Dirham dos Emirados' },
  { code: 'BRL-BBD', name: 'Real Brasileiro/Dólar de Barbados' },
  { code: 'BRL-BHD', name: 'Real Brasileiro/Dinar do Bahrein' },
  { code: 'BRL-CNY', name: 'Real Brasileiro/Yuan Chinês' },
  { code: 'BRL-CZK', name: 'Real Brasileiro/Coroa Checa' },
  { code: 'BRL-EGP', name: 'Real Brasileiro/Libra Egípcia' },
  { code: 'BRL-GBP', name: 'Real Brasileiro/Libra Esterlina' },
  { code: 'BRL-HUF', name: 'Real Brasileiro/Florim Húngaro' },
  { code: 'BRL-IDR', name: 'Real Brasileiro/Rupia Indonésia' },
  { code: 'BRL-ILS', name: 'Real Brasileiro/Novo Shekel Israelense' },
  { code: 'BRL-INR', name: 'Real Brasileiro/Rúpia Indiana' },
  { code: 'BRL-ISK', name: 'Real Brasileiro/Coroa Islandesa' },
  { code: 'BRL-JMD', name: 'Real Brasileiro/Dólar Jamaicano' },
  { code: 'BRL-JOD', name: 'Real Brasileiro/Dinar Jordaniano' },
  { code: 'BRL-KES', name: 'Real Brasileiro/Shilling Queniano' },
  { code: 'BRL-KRW', name: 'Real Brasileiro/Won Sul-Coreano' },
  { code: 'BRL-LBP', name: 'Real Brasileiro/Libra Libanesa' },
  { code: 'BRL-LKR', name: 'Real Brasileiro/Rúpia de Sri Lanka' },
  { code: 'BRL-MAD', name: 'Real Brasileiro/Dirham Marroquino' },
  { code: 'BRL-MYR', name: 'Real Brasileiro/Ringgit Malaio' },
  { code: 'BRL-NAD', name: 'Real Brasileiro/Dólar Namíbio' },
  { code: 'BRL-NOK', name: 'Real Brasileiro/Coroa Norueguesa' },
  { code: 'BRL-NPR', name: 'Real Brasileiro/Rúpia Nepalesa' },
  { code: 'BRL-NZD', name: 'Real Brasileiro/Dólar Neozelandês' },
  { code: 'BRL-OMR', name: 'Real Brasileiro/Rial Omanense' },
  { code: 'BRL-PAB', name: 'Real Brasileiro/Balboa Panamenho' },
  { code: 'BRL-PHP', name: 'Real Brasileiro/Peso Filipino' },
  { code: 'BRL-PKR', name: 'Real Brasileiro/Rúpia Paquistanesa' },
  { code: 'BRL-PLN', name: 'Real Brasileiro/Zlóti Polonês' },
  { code: 'BRL-QAR', name: 'Real Brasileiro/Rial Catarense' },
  { code: 'BRL-RON', name: 'Real Brasileiro/Leu Romeno' },
  { code: 'BRL-RUB', name: 'Real Brasileiro/Rublo Russo' },
  { code: 'BRL-SAR', name: 'Real Brasileiro/Riyal Saudita' },
  { code: 'BRL-SEK', name: 'Real Brasileiro/Coroa Sueca' },
  { code: 'BRL-THB', name: 'Real Brasileiro/Baht Tailandês' },
  { code: 'BRL-TRY', name: 'Real Brasileiro/Nova Lira Turca' },
  { code: 'BRL-VEF', name: 'Real Brasileiro/Bolívar Venezuelano' },
  { code: 'BRL-XAF', name: 'Real Brasileiro/Franco CFA Central' },
  { code: 'BRL-XCD', name: 'Real Brasileiro/Dólar do Caribe Oriental' },
  { code: 'BRL-XOF', name: 'Real Brasileiro/Franco CFA Ocidental' },
  { code: 'BRL-ZAR', name: 'Real Brasileiro/Rand Sul-Africano' },
  { code: 'BRL-TWD', name: 'Real Brasileiro/Dólar Taiuanês' },
  { code: 'DKK-BRL', name: 'Coroa Dinamarquesa/Real Brasileiro' },
  { code: 'HKD-BRL', name: 'Dólar de Hong Kong/Real Brasileiro' },
  { code: 'MXN-BRL', name: 'Peso Mexicano/Real Brasileiro' },
  { code: 'NOK-BRL', name: 'Coroa Norueguesa/Real Brasileiro' },
  { code: 'NZD-BRL', name: 'Dólar Neozelandês/Real Brasileiro' },
  { code: 'PLN-BRL', name: 'Zlóti Polonês/Real Brasileiro' },
  { code: 'SAR-BRL', name: 'Riyal Saudita/Real Brasileiro' },
  { code: 'SEK-BRL', name: 'Coroa Sueca/Real Brasileiro' },
  { code: 'THB-BRL', name: 'Baht Tailandês/Real Brasileiro' },
  { code: 'TRY-BRL', name: 'Nova Lira Turca/Real Brasileiro' },
  { code: 'TWD-BRL', name: 'Dólar Taiuanês/Real Brasileiro' },
  { code: 'VEF-BRL', name: 'Bolívar Venezuelano/Real Brasileiro' },
  { code: 'ZAR-BRL', name: 'Rand Sul-Africano/Real Brasileiro' },
  { code: 'BRL-PYG', name: 'Real Brasileiro/Guarani Paraguaio' },
  { code: 'BRL-UYU', name: 'Real Brasileiro/Peso Uruguaio' },
  { code: 'BRL-COP', name: 'Real Brasileiro/Peso Colombiano' },
  { code: 'BRL-PEN', name: 'Real Brasileiro/Sol do Peru' },
  { code: 'BRL-BOB', name: 'Real Brasileiro/Boliviano' },
  { code: 'CLP-BRL', name: 'Peso Chileno/Real Brasileiro' },
  { code: 'PYG-BRL', name: 'Guarani Paraguaio/Real Brasileiro' },
  { code: 'UYU-BRL', name: 'Peso Uruguaio/Real Brasileiro' },
  { code: 'COP-BRL', name: 'Peso Colombiano/Real Brasileiro' },
  { code: 'PEN-BRL', name: 'Sol do Peru/Real Brasileiro' },
  { code: 'BOB-BRL', name: 'Boliviano/Real Brasileiro' },
  { code: 'RUB-BRL', name: 'Rublo Russo/Real Brasileiro' },
  { code: 'INR-BRL', name: 'Rúpia Indiana/Real Brasileiro' },
  { code: 'EUR-GBP', name: 'Euro/Libra Esterlina' },
  { code: 'EUR-JPY', name: 'Euro/Iene Japonês' },
  { code: 'EUR-CHF', name: 'Euro/Franco Suíço' },
  { code: 'EUR-AUD', name: 'Euro/Dólar Australiano' },
  { code: 'EUR-CAD', name: 'Euro/Dólar Canadense' },
  { code: 'EUR-NOK', name: 'Euro/Coroa Norueguesa' },
  { code: 'EUR-DKK', name: 'Euro/Coroa Dinamarquesa' },
  { code: 'EUR-PLN', name: 'Euro/Zlóti Polonês' },
  { code: 'EUR-NZD', name: 'Euro/Dólar Neozelandês' },
  { code: 'EUR-SEK', name: 'Euro/Coroa Sueca' },
  { code: 'EUR-ILS', name: 'Euro/Novo Shekel Israelense' }
]
